version: '2'
services:

  nginx:
    build:
      context: ./
      dockerfile: nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8801:80"
    links:
      - php-fpm
    restart: always

  php-fpm:
    build:
      context: ./
      dockerfile: php.docker
    volumes:
      - ./:/var/www
    environment:
      - "XDEBUG_CONFIG=remote_host=192.168.0.103"
